services:
  go:
    build: ./
    container_name: go_jwt_container
    volumes:
    - ./:/src
    ports:
    - "8080:8080"
    tty: true
    networks:
      - back-db
    depends_on:
      - db
  db:
    image: mysql
    container_name: db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    networks:
      - back-db

networks:
  back-db:
    name: back-db
    driver: bridge